version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosec
    - bidichk
    - errorlint
    - bodyclose
    - unconvert
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
    errcheck:
      check-type-assertions: true
      check-blank: true
    unused:
      parameters-are-used: false

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m