version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosec
    - bidichk
    - errorlint
    - bodyclose
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1005"
        - "-ST1023"
        - "-QF1011"
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - os.RemoveAll
        - io.Closer.Close
        - (io/fs.File).Close
        - (mime/multipart.File).Close
        - (*os.File).Close
        - (*database/sql.DB).Close
    unused:
      parameters-are-used: true
    gosec:
      severity: "medium"
      confidence: "medium"
      excludes:
        - G104
        - G115


formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m