name: Build Golang

on:
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Download React artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: backend/golang/dist

      - name: Download Unity artifacts
        uses: actions/download-artifact@v4
        with:
          name: unity-build
          path: backend/golang/dist/webgl

      - name: Build Golang
        run: |
          go build -o cursed_frame .
        working-directory: ./backend/golang

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-build
          path: backend/golang/cursed_frame
          retention-days: 1
